{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e0b3acc-addb-44d3-97e1-3996c8ec7a58",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import plotly.express as px  # For viz if needed\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "\n",
    "# Load models/preprocessors\n",
    "@st.cache_resource\n",
    "def load_models():\n",
    "    le = joblib.load('label_encoder.pkl')\n",
    "    scaler = joblib.load('scaler.pkl')\n",
    "    models = {name: joblib.load(f'{name.replace(\" \", \"_\").replace(\"-\", \"_\")}.pkl') \n",
    "              for name in ['Logistic Regression', 'Decision Tree', 'KNN', 'Naive Bayes', 'Random Forest', 'XGBoost']}\n",
    "    results_df = pd.read_csv('results.csv')  # Save results_df.to_csv('results.csv') from Step 3\n",
    "    return le, scaler, models, results_df\n",
    "\n",
    "le, scaler, models, results_df = load_models()\n",
    "\n",
    "st.title(\"Customer Churn Prediction App\")\n",
    "\n",
    "# After load_models()\n",
    "st.header(\"EDA Insights\")\n",
    "st.image('eda_charts.png')  # Upload this file to repo\n",
    "\n",
    "# Feature importance (for best model, e.g., RF)\n",
    "if st.checkbox(\"Show Feature Importance\"):\n",
    "    rf_model = models['Random Forest']\n",
    "    importances = pd.DataFrame({'Feature': X.columns, 'Importance': rf_model.feature_importances_}).sort_values('Importance', ascending=False)\n",
    "    fig = px.bar(importances.head(10), x='Importance', y='Feature', orientation='h', title=\"Top 10 Feature Importances\")\n",
    "    st.plotly_chart(fig)\n",
    "\n",
    "# Metrics display\n",
    "st.header(\"Model Comparison Metrics\")\n",
    "st.dataframe(results_df)\n",
    "\n",
    "# Confusion matrix image\n",
    "st.image('confusion_matrix.png')\n",
    "\n",
    "# Upload test data\n",
    "uploaded_file = st.file_uploader(\"Upload test CSV (e.g., test.csv)\", type='csv')\n",
    "if uploaded_file:\n",
    "    test_data = pd.read_csv(uploaded_file)\n",
    "    st.write(\"Test data preview:\", test_data.head())\n",
    "    \n",
    "    # Preprocess\n",
    "    test_data = test_data.drop('customerID', axis=1, errors='ignore')\n",
    "    cat_cols = test_data.select_dtypes(include=['object']).columns\n",
    "    for col in cat_cols:\n",
    "        test_data[col] = le.fit_transform(test_data[col].astype(str))  # Re-fit if new cats\n",
    "    num_cols = test_data.select_dtypes(include=[np.number]).columns\n",
    "    test_data[num_cols] = scaler.transform(test_data[num_cols])\n",
    "    \n",
    "    # Model selection\n",
    "    model_name = st.selectbox(\"Select Model\", list(models.keys()))\n",
    "    model = models[model_name]\n",
    "    \n",
    "    # Predict\n",
    "    if st.button(\"Predict Churn\"):\n",
    "        preds = model.predict(test_data)\n",
    "        probs = model.predict_proba(test_data)[:, 1]\n",
    "        test_data['Churn_Pred'] = ['Yes' if p==1 else 'No' for p in preds]\n",
    "        test_data['Churn_Prob'] = probs\n",
    "        st.dataframe(test_data[['Churn_Pred', 'Churn_Prob']])\n",
    "        \n",
    "        # Viz\n",
    "        fig = px.histogram(test_data, x='Churn_Prob', nbins=20, title=\"Churn Probability Distribution\")\n",
    "        st.plotly_chart(fig)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
